name: Physicon

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.G_TOKEN }}" | docker login ghcr.io -u vansd --password-stdin

      - name: Build the Docker image
        run: docker build -t ghcr.io/vansd/physicon2/physicon:latest .

      - name: Push the Docker image
        run: docker push ghcr.io/vansd/physicon2/physicon:latest
